rtl/mcore/mcore_pkg.sv
rtl/mcore/mcore_fifo.sv
rtl/mcore/mcore_cmd.sv
rtl/mcore/mcore_fetch.sv
rtl/mcore/mcore_compute.sv
rtl/mcore/mcore_writeback.sv
rtl/mcore/mcore.sv
tb/mcore_prog_pkg.sv
tb/mcore_tb.sv
